version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network

  backend_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - postgres_db
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge